// ********RoostGPT********
/*
Test generated by RoostGPT for test gotest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_GetComments_d7c78dda64
ROOST_METHOD_SIG_HASH=ArticleStore_GetComments_af08ddd59e

FUNCTION_DEF=func (s *ArticleStore) GetComments(m *model.Article) ([ // GetComments gets coments of the article
]model.Comment, error) 
Scenario 1: Successful retrieval of comments for a given article

Details:
  Description: This test is meant to check if the function correctly retrieves all comments associated with a given article. The test will simulate a scenario where the database contains a set of comments linked to a specific article.

Execution:
  Arrange: Mock the database to contain a set of comments associated with a specific article. Create an instance of the ArticleStore and an instance of the Article model with a valid ID that matches the article in the mock database.
  Act: Invoke the GetComments function with the Article instance as a parameter.
  Assert: Use Go testing facilities to verify that the returned slice of comments matches the comments in the mock database and that no error is returned.

Validation:
  The assertion checks that the function correctly retrieves all comments associated with the given article. This test is important to ensure that the function behaves as expected in normal operation and successfully retrieves comments from the database.

Scenario 2: Article with no comments

Details:
  Description: This test is meant to check if the function correctly handles a scenario where the given article has no associated comments. The test will simulate a scenario where the database contains an article with no comments.

Execution:
  Arrange: Mock the database to contain an article with no associated comments. Create an instance of the ArticleStore and an instance of the Article model with a valid ID that matches the article in the mock database.
  Act: Invoke the GetComments function with the Article instance as a parameter.
  Assert: Use Go testing facilities to verify that the returned slice of comments is empty and that no error is returned.

Validation:
  The assertion checks that the function correctly handles a scenario where the given article has no comments. This test is important to ensure that the function behaves as expected when an article has no comments.

Scenario 3: Article not found in the database

Details:
  Description: This test is meant to check if the function correctly handles a scenario where the given article is not found in the database. The test will simulate a scenario where the database does not contain the given article.

Execution:
  Arrange: Mock the database to not contain the given article. Create an instance of the ArticleStore and an instance of the Article model with an ID that does not match any article in the mock database.
  Act: Invoke the GetComments function with the Article instance as a parameter.
  Assert: Use Go testing facilities to verify that an error is returned.

Validation:
  The assertion checks that the function correctly handles a scenario where the given article is not found in the database. This test is important to ensure that the function behaves as expected when the given article does not exist in the database.

Scenario 4: Database error during retrieval of comments

Details:
  Description: This test is meant to check if the function correctly handles a scenario where a database error occurs during the retrieval of comments. The test will simulate a scenario where a database error occurs when attempting to retrieve comments.

Execution:
  Arrange: Mock the database to return an error when attempting to retrieve comments. Create an instance of the ArticleStore and an instance of the Article model with a valid ID.
  Act: Invoke the GetComments function with the Article instance as a parameter.
  Assert: Use Go testing facilities to verify that an error is returned.

Validation:
  The assertion checks that the function correctly handles a scenario where a database error occurs during the retrieval of comments. This test is important to ensure that the function behaves as expected when a database error occurs.
*/

// ********RoostGPT********


package store

import (
	"errors"
	"testing"
	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)







func TestArticleStoreGetComments(t *testing.T) {

	testCases := []struct {
		name     string
		article  *model.Article
		mock     func()
		expected []model.Comment
		wantErr  bool
	}{
		{

			name:    "Successful retrieval of comments",
			article: &model.Article{Model: gorm.Model{ID: 1}},
			mock: func() {
				rows := sqlmock.NewRows([]string{"id", "body", "user_id", "article_id"}).
					AddRow(1, "comment1", 1, 1).
					AddRow(2, "comment2", 1, 1)
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WithArgs(1).WillReturnRows(rows)
			},
			expected: []model.Comment{
				{Model: gorm.Model{ID: 1}, Body: "comment1", UserID: 1, ArticleID: 1},
				{Model: gorm.Model{ID: 2}, Body: "comment2", UserID: 1, ArticleID: 1},
			},
			wantErr: false,
		},
		{

			name:    "Article with no comments",
			article: &model.Article{Model: gorm.Model{ID: 2}},
			mock: func() {
				rows := sqlmock.NewRows([]string{"id", "body", "user_id", "article_id"})
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WithArgs(2).WillReturnRows(rows)
			},
			expected: []model.Comment{},
			wantErr:  false,
		},
		{

			name:    "Article not found in the database",
			article: &model.Article{Model: gorm.Model{ID: 3}},
			mock: func() {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WithArgs(3).
					WillReturnError(gorm.ErrRecordNotFound)
			},
			expected: nil,
			wantErr:  true,
		},
		{

			name:    "Database error during retrieval of comments",
			article: &model.Article{Model: gorm.Model{ID: 4}},
			mock: func() {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WithArgs(4).
					WillReturnError(errors.New("database error"))
			},
			expected: nil,
			wantErr:  true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, _ := sqlmock.New()
			GormDB, _ := gorm.Open("postgres", db)
			defer func() {
				db.Close()
			}()

			tc.mock()

			store := &ArticleStore{db: GormDB}

			comments, err := store.GetComments(tc.article)

			if tc.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
				assert.Equal(t, tc.expected, comments)
			}
		})
	}
}