// ********RoostGPT********
/*
Test generated by RoostGPT for test GoReadOnlyTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=ArticleStore_GetArticles_101b7250e8
ROOST_METHOD_SIG_HASH=ArticleStore_GetArticles_91bc0a6760

FUNCTION_DEF=func (s *ArticleStore) GetArticles(tagName, username string, favoritedBy *model.User, limit, offset int64) ([ // GetArticles get global articles
]model.Article, error)
Scenario 1: Articles by Specific Username

Details:
  Description: This test is meant to check if the function returns articles written by a specific user when the username parameter is provided.
Execution:
  Arrange: Mock the database, and prepare data by creating records for some articles belonging to a user with the provided username.
  Act: Invoke the GetArticles function with the username parameter set to the username of the created user and the other parameters left empty or zero.
  Assert: Use go testing to check that the return slice only contains articles by the user with the given username.
Validation:
  The comparison to check if the returned articles are by the user with the provided username is valid because the function is expected to filter articles by author if the username parameter is not empty. This ensures that the function correctly filters articles by author.

Scenario 2: Articles with Specific Tag

Details:
  Description: This test is meant to check if the function returns articles with a specific tag when the tagName parameter is provided.
Execution:
  Arrange: Mock the database, and add article records tagged with a specific tag.
  Act: Invoke the GetArticles function with the tagName parameter set to the tag name and the other parameters left empty or zero.
  Assert: Verify that the returned articles are the ones that are tagged with the provided tag.
Validation:
  The logic behind the assertion is that the function should return articles tagged with the provided tag name. This test is important to verify that the function correctly filters articles by tag.

Scenario 3: Articles Favorited by User

Details:
  Description: This test is meant to check if the function returns articles favorited by a specific user.
Execution:
  Arrange: Mock the database, create a user record and add records of some articles favorited by the created user.
  Act: Invoke the GetArticles function with the favoritedBy parameter set to the created user and the other parameters left empty or zero.
  Assert: Verify that the articles returned by function are the ones favorited by the provided user.
Validation:
  The function should return articles favorited by the provided user. This test validates the function's ability to correctly fetch articles favorited by a specific user.

Scenario 4: Error Handling

Details:
  Description: This test is meant to check if the function returns an error message if there is an error in the database query.
Execution:
  Arrange: Create a mocked database that returns an error on queries.
  Act: Invoke the GetArticles function with any of the parameters.
  Assert: Check that the error returned is the error you mocked your database to return.
Validation:
  The function should handle errors, and return them to the caller instead of crashing the application. This test validates that the function is correctly handling errors which could occur during data fetching or processing.
*/

// ********RoostGPT********

package store

import (
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)

func (s *ArticleStore) GetArticles(tagName, username string, favoritedBy *model.User, limit, offset int64) ([]model.Article, error) {
	d := s.db.Preload("Author")
	if username != "" {
		d = d.Joins("join users on articles.user_id = users.id").Where("users.username = ?", username)
	}
	if tagName != "" {
		d = d.Joins("join article_tags on articles.id = article_tags.article_id "+"join tags on tags.id = article_tags.tag_id").Where("tags.name = ?", tagName)
	}
	if favoritedBy != nil {
		rows, err := s.db.Select("article_id").Table("favorite_articles").Where("user_id = ?", favoritedBy.ID).Offset(offset).Limit(limit).Rows()
		if err != nil {
			return []model.Article{}, err
		}
		defer rows.Close()
		var ids []uint
		for rows.Next() {
			var id uint
			rows.Scan(&id)
			ids = append(ids, id)
		}
		d = d.Where("id in (?)", ids)
	}
	d = d.Offset(offset).Limit(limit)
	var as []model.Article
	err := d.Find(&as).Error
	return as, err
}
func TestArticleStoreGetArticles(t *testing.T) {

	mockDB, mock, _ := sqlmock.New()
	defer mockDB.Close()
	gormDB, _ := gorm.Open("postgres", mockDB)

	mockArticles := []model.Article{
		{
			Slug:        "article1",
			Title:       "article1",
			Description: "desc1",
			Body:        "body1",
		},
		{
			Slug:        "article2",
			Title:       "article2",
			Description: "desc2",
			Body:        "body2",
		},
	}

	mockUser := model.User{Username: "usertest"}

	testCases := []struct {
		desc                 string
		tagName              string
		username             string
		favoritedBy          *model.User
		offset               int64
		limit                int64
		mockError            error
		mockReturnedArticles []model.Article
		expectedError        error
		expectedReturnedArts []model.Article
	}{
		{
			desc:                 "Scenario 1: Articles by Specific Username",
			username:             "usertest",
			mockReturnedArticles: mockArticles,
			expectedReturnedArts: mockArticles,
		},
		{
			desc:                 "Scenario 2: Articles with Specific Tag",
			tagName:              "tagtest",
			mockReturnedArticles: mockArticles,
			expectedReturnedArts: mockArticles,
		},
		{
			desc:                 "Scenario 3: Articles Favorited by User",
			favoritedBy:          &mockUser,
			mockReturnedArticles: mockArticles,
			expectedReturnedArts: mockArticles,
		},
		{
			desc:          "Scenario 4: Error Handling",
			mockError:     gorm.ErrRecordNotFound,
			expectedError: gorm.ErrRecordNotFound,
		},
	}

	articleStore := ArticleStore{db: gormDB}

	for _, tC := range testCases {
		t.Run(tC.desc, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			mock.ExpectQuery("^SELECT (.+) FROM").
				WillReturnRows(sqlmock.NewRows([]string{"slug", "title", "description", "body"}).
					AddRow(mockArticles[0].Slug, mockArticles[0].Title, mockArticles[0].Description, mockArticles[0].Body).
					AddRow(mockArticles[1].Slug, mockArticles[1].Title, mockArticles[1].Description, mockArticles[1].Body))

			if tC.mockError != nil {
				mock.ExpectQuery("^SELECT (.+) FROM").WillReturnError(tC.mockError)
			}

			articles, err := articleStore.GetArticles(tC.tagName, tC.username, tC.favoritedBy, tC.limit, tC.offset)
			if tC.expectedError != nil {
				assert.Error(t, err)
				assert.Equal(t, tC.expectedError, err)
			} else {
				assert.NoError(t, err)
				assert.Equal(t, tC.expectedReturnedArts, articles)
			}
		})
	}
}
