// ********RoostGPT********
/*
Test generated by RoostGPT for test gotest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_GetCommentByID_7ecaa81f20
ROOST_METHOD_SIG_HASH=ArticleStore_GetCommentByID_f6f8a51973

FUNCTION_DEF=func (s *ArticleStore) GetCommentByID(id uint) (*model.Comment, error) // GetCommentByID finds an comment from id

Scenario 1: Successful retrieval of a comment by ID

Details:
  Description: This test is meant to check if the function successfully retrieves a comment from the database when provided with a valid ID. The target scenario is a normal operation where the ID exists in the database.

Execution:
  Arrange: Mock the database to return a specific comment when queried with a particular ID.
  Act: Invoke the GetCommentByID function with the ID used in the mock setup.
  Assert: Check that the returned comment matches the one set up in the mock and that no error is returned.

Validation:
  The assertion checks that the function correctly retrieves the comment from the database. This is important as it verifies the function's ability to fetch comments, which is crucial for displaying them to users.

Scenario 2: Attempt to retrieve a comment with a non-existent ID

Details:
  Description: This test is meant to check how the function handles a situation where it's asked to retrieve a comment using an ID that doesn't exist in the database. The target scenario is an edge case where the ID is not found.

Execution:
  Arrange: Mock the database to return an error when queried with a non-existent ID.
  Act: Invoke the GetCommentByID function with the non-existent ID.
  Assert: Check that the function returns an error indicating that the comment was not found.

Validation:
  The assertion checks that the function correctly handles the case where a comment with the provided ID doesn't exist. This is important as it ensures that the function can gracefully handle errors and provide useful feedback to the caller.

Scenario 3: Database error during retrieval of a comment

Details:
  Description: This test is meant to check how the function handles a situation where a database error occurs while trying to retrieve a comment. The target scenario is an error handling case where there's a problem with the database operation.

Execution:
  Arrange: Mock the database to return a general error when queried with any ID.
  Act: Invoke the GetCommentByID function with any ID.
  Assert: Check that the function returns the same error that was mocked.

Validation:
  The assertion checks that the function correctly propagates database errors up to the caller. This is important as it allows the caller to handle these errors appropriately, which could include logging the error, retrying the operation, or providing feedback to the user.
*/

// ********RoostGPT********


package store

import (
	"errors"
	"testing"
	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)







func TestArticleStoreGetCommentById(t *testing.T) {

	testCases := []struct {
		name           string
		mockFunc       func(mock sqlmock.Sqlmock)
		id             uint
		expectedResult *model.Comment
		expectedError  error
	}{
		{
			name: "Successful retrieval of a comment by ID",
			mockFunc: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "body", "user_id", "article_id"}).
					AddRow(1, "Test Comment", 1, 1)
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WillReturnRows(rows)
			},
			id:             1,
			expectedResult: &model.Comment{Model: gorm.Model{ID: 1}, Body: "Test Comment", UserID: 1, ArticleID: 1},
			expectedError:  nil,
		},
		{
			name: "Attempt to retrieve a comment with a non-existent ID",
			mockFunc: func(mock sqlmock.Sqlmock) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WillReturnError(gorm.ErrRecordNotFound)
			},
			id:             2,
			expectedResult: nil,
			expectedError:  gorm.ErrRecordNotFound,
		},
		{
			name: "Database error during retrieval of a comment",
			mockFunc: func(mock sqlmock.Sqlmock) {
				mock.ExpectQuery("^SELECT (.+) FROM \"comments\" WHERE (.+)").WillReturnError(errors.New("database error"))
			},
			id:             3,
			expectedResult: nil,
			expectedError:  errors.New("database error"),
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
			}
			defer db.Close()

			gormDB, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening gorm database", err)
			}

			tc.mockFunc(mock)

			store := &ArticleStore{db: gormDB}

			result, err := store.GetCommentByID(tc.id)

			assert.Equal(t, tc.expectedResult, result)
			assert.Equal(t, tc.expectedError, err)
		})
	}
}
