// ********RoostGPT********
/*
Test generated by RoostGPT for test gotest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_DeleteComment_effbcb38aa
ROOST_METHOD_SIG_HASH=ArticleStore_DeleteComment_d3c99623e4

FUNCTION_DEF=func (s *ArticleStore) DeleteComment(m *model.Comment) error // DeleteComment deletes an comment

Scenario 1: Successful Deletion of a Comment

Details:
  Description: This test is meant to check if the function correctly deletes a comment from the database. The target scenario is when a valid comment model is passed to the function.

Execution:
  Arrange: Create a mock of the database and a comment model. The mock should be set to expect a Delete call with the comment model and return no error.
  Act: Invoke the DeleteComment function with the comment model.
  Assert: Use Go testing facilities to verify that the mock database's Delete method was called with the correct parameters and that no error was returned by the function.

Validation:
  The assertion checks that the function correctly interacts with the database to delete the comment. This test is important to ensure that the function can successfully delete comments from the database, which is a crucial part of managing user-generated content in the application.

Scenario 2: Deletion of a Non-Existent Comment

Details:
  Description: This test is meant to check how the function handles the scenario where a non-existent comment is passed for deletion. The target scenario is when a comment model that does not exist in the database is passed to the function.

Execution:
  Arrange: Create a mock of the database and a comment model. The mock should be set to expect a Delete call with the comment model and return an error indicating that the comment does not exist.
  Act: Invoke the DeleteComment function with the comment model.
  Assert: Use Go testing facilities to verify that the mock database's Delete method was called with the correct parameters and that the function returned the correct error.

Validation:
  The assertion checks that the function correctly handles the error returned by the database and propagates it to the caller. This test is important to ensure that the function can handle errors from the database and correctly inform the caller about the failure to delete a non-existent comment.

Scenario 3: Database Error During Deletion

Details:
  Description: This test is meant to check how the function handles a database error during the deletion process. The target scenario is when a database error occurs while trying to delete a comment.

Execution:
  Arrange: Create a mock of the database and a comment model. The mock should be set to expect a Delete call with the comment model and return a database error.
  Act: Invoke the DeleteComment function with the comment model.
  Assert: Use Go testing facilities to verify that the mock database's Delete method was called with the correct parameters and that the function returned the correct error.

Validation:
  The assertion checks that the function correctly handles the database error and propagates it to the caller. This test is important to ensure that the function can handle unexpected errors during the deletion process and correctly inform the caller about the failure.
*/

// ********RoostGPT********


package store

import (
	"errors"
	"testing"
	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)







func TestArticleStoreDeleteComment(t *testing.T) {

	tests := []struct {
		name        string
		comment     *model.Comment
		mockDB      func(mock sqlmock.Sqlmock, comment *model.Comment)
		expectedErr error
	}{
		{
			name:    "Successful Deletion of a Comment",
			comment: &model.Comment{Model: gorm.Model{ID: 1}},
			mockDB: func(mock sqlmock.Sqlmock, comment *model.Comment) {
				mock.ExpectBegin()
				mock.ExpectExec("DELETE").WithArgs(comment.ID).WillReturnResult(sqlmock.NewResult(1, 1))
				mock.ExpectCommit()
			},
			expectedErr: nil,
		},
		{
			name:    "Deletion of a Non-Existent Comment",
			comment: &model.Comment{Model: gorm.Model{ID: 2}},
			mockDB: func(mock sqlmock.Sqlmock, comment *model.Comment) {
				mock.ExpectBegin()
				mock.ExpectExec("DELETE").WithArgs(comment.ID).WillReturnError(gorm.ErrRecordNotFound)
				mock.ExpectRollback()
			},
			expectedErr: gorm.ErrRecordNotFound,
		},
		{
			name:    "Database Error During Deletion",
			comment: &model.Comment{Model: gorm.Model{ID: 3}},
			mockDB: func(mock sqlmock.Sqlmock, comment *model.Comment) {
				mock.ExpectBegin()
				mock.ExpectExec("DELETE").WithArgs(comment.ID).WillReturnError(errors.New("database error"))
				mock.ExpectRollback()
			},
			expectedErr: errors.New("database error"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("failed to open mock sql db: %v", err)
			}
			defer db.Close()

			gdb, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("failed to open gorm db: %v", err)
			}

			tt.mockDB(mock, tt.comment)

			store := &ArticleStore{db: gdb}
			err = store.DeleteComment(tt.comment)

			assert.Equal(t, tt.expectedErr, err)
			if err := mock.ExpectationsWereMet(); err != nil {
				t.Errorf("there were unfulfilled expectations: %s", err)
			}
		})
	}
}
