// ********RoostGPT********
/*
Test generated by RoostGPT for test gotest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_DeleteComment_effbcb38aa
ROOST_METHOD_SIG_HASH=ArticleStore_DeleteComment_d3c99623e4

FUNCTION_DEF=func (s *ArticleStore) DeleteComment(m *model.Comment) error // DeleteComment deletes an comment

Scenario 1: Successful Deletion of Comment

Details:
  Description: This test is meant to check if the function successfully deletes a comment from the database. The target scenario is when the comment exists in the database and is valid.

Execution:
  Arrange: Create a mock database and a mock comment. Add the comment to the database.
  Act: Invoke the DeleteComment function with the mock comment as a parameter.
  Assert: Use Go testing facilities to verify that the comment no longer exists in the database.

Validation:
  The assertion checks if the comment was successfully deleted from the database. The expected result is that the comment no longer exists in the database. This test is important to ensure that the function correctly deletes comments from the database when they are valid and exist in the database.

Scenario 2: Deletion of Non-Existent Comment

Details:
  Description: This test is meant to check if the function handles the deletion of a comment that does not exist in the database. The target scenario is when the comment does not exist in the database.

Execution:
  Arrange: Create a mock database and a mock comment. Do not add the comment to the database.
  Act: Invoke the DeleteComment function with the mock comment as a parameter.
  Assert: Use Go testing facilities to verify that an error is returned.

Validation:
  The assertion checks if an error is returned when trying to delete a comment that does not exist in the database. The expected result is that an error is returned. This test is important to ensure that the function correctly handles the scenario where a comment does not exist in the database.

Scenario 3: Deletion of Invalid Comment

Details:
  Description: This test is meant to check if the function handles the deletion of an invalid comment. The target scenario is when the comment is invalid.

Execution:
  Arrange: Create a mock database and an invalid mock comment. Add the invalid comment to the database.
  Act: Invoke the DeleteComment function with the invalid mock comment as a parameter.
  Assert: Use Go testing facilities to verify that an error is returned.

Validation:
  The assertion checks if an error is returned when trying to delete an invalid comment. The expected result is that an error is returned. This test is important to ensure that the function correctly handles the scenario where a comment is invalid.
*/

// ********RoostGPT********


package store

import (
	"errors"
	"testing"
	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
)







func TestArticleStoreDeleteComment(t *testing.T) {
	tests := []struct {
		name    string
		comment *model.Comment
		mock    func()
		wantErr bool
	}{
		{
			name: "Successful Deletion of Comment",
			comment: &model.Comment{
				Model: gorm.Model{
					ID: 1,
				},
			},
			mock: func() {
				sqlmock.ExpectExec("DELETE FROM \"comments\" WHERE \"comments\".\"deleted_at\" IS NULL AND \"comments\".\"id\" = $1").
					WithArgs(1).
					WillReturnResult(sqlmock.NewResult(1, 1))
			},
			wantErr: false,
		},
		{
			name: "Deletion of Non-Existent Comment",
			comment: &model.Comment{
				Model: gorm.Model{
					ID: 2,
				},
			},
			mock: func() {
				sqlmock.ExpectExec("DELETE FROM \"comments\" WHERE \"comments\".\"deleted_at\" IS NULL AND \"comments\".\"id\" = $1").
					WithArgs(2).
					WillReturnError(errors.New("record not found"))
			},
			wantErr: true,
		},
		{
			name: "Deletion of Invalid Comment",
			comment: &model.Comment{
				Model: gorm.Model{
					ID: 3,
				},
			},
			mock: func() {
				sqlmock.ExpectExec("DELETE FROM \"comments\" WHERE \"comments\".\"deleted_at\" IS NULL AND \"comments\".\"id\" = $1").
					WithArgs(3).
					WillReturnError(errors.New("invalid comment"))
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
			}
			defer db.Close()

			gormDB, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening gorm database", err)
			}

			tt.mock()

			store := &ArticleStore{
				db: gormDB,
			}

			err = store.DeleteComment(tt.comment)
			if (err != nil) != tt.wantErr {
				t.Errorf("ArticleStore.DeleteComment() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if err := mock.ExpectationsWereMet(); err != nil {
				t.Errorf("there were unfulfilled expectations: %s", err)
			}
		})
	}
}
