// ********RoostGPT********
/*
Test generated by RoostGPT for test gotest1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=NewUserStore_fb599438e5
ROOST_METHOD_SIG_HASH=NewUserStore_c0075221af

FUNCTION_DEF=func NewUserStore(db *gorm.DB) *UserStore // NewUserStore returns a new UserStore

Scenario 1: Successful creation of a new UserStore

Details:
  Description: This test is meant to check if the NewUserStore function can successfully create a new UserStore instance when provided with a valid gorm.DB instance.
Execution:
  Arrange: Create a mock gorm.DB instance.
  Act: Invoke the NewUserStore function with the mock gorm.DB instance as the parameter.
  Assert: Use Go testing facilities to verify that the returned UserStore instance is not nil and that its db field is the same as the mock gorm.DB instance.
Validation:
  The assertion checks if the NewUserStore function correctly assigns the provided gorm.DB instance to the db field of the new UserStore instance. This test is important to ensure that the NewUserStore function can correctly initialize a new UserStore instance.

Scenario 2: Creation of a new UserStore with a nil gorm.DB instance

Details:
  Description: This test is meant to check if the NewUserStore function can handle a nil gorm.DB instance and still return a valid UserStore instance.
Execution:
  Arrange: No arrangement is needed as we are passing a nil value.
  Act: Invoke the NewUserStore function with nil as the parameter.
  Assert: Use Go testing facilities to verify that the returned UserStore instance is not nil and that its db field is nil.
Validation:
  The assertion checks if the NewUserStore function correctly handles a nil gorm.DB instance by assigning nil to the db field of the new UserStore instance. This test is important to ensure that the NewUserStore function can handle edge cases where a nil gorm.DB instance is provided.

Scenario 3: Multiple invocations of the NewUserStore function

Details:
  Description: This test is meant to check if the NewUserStore function can correctly create multiple distinct UserStore instances when invoked multiple times with different gorm.DB instances.
Execution:
  Arrange: Create multiple mock gorm.DB instances.
  Act: Invoke the NewUserStore function multiple times, each time with a different mock gorm.DB instance as the parameter.
  Assert: Use Go testing facilities to verify that each returned UserStore instance is not nil, that its db field is the same as the corresponding mock gorm.DB instance, and that the UserStore instances are distinct from each other.
Validation:
  The assertion checks if the NewUserStore function correctly creates distinct UserStore instances for each invocation. This test is important to ensure that the NewUserStore function does not reuse or share state between different UserStore instances.
*/

// ********RoostGPT********


package store

import (
	"testing"
	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/stretchr/testify/assert"
)







func TestNewUserStore(t *testing.T) {

	testCases := []struct {
		name     string
		db       *gorm.DB
		expected *UserStore
	}{
		{
			name: "Successful creation of a new UserStore",
			db:   &gorm.DB{},
			expected: &UserStore{
				db: &gorm.DB{},
			},
		},
		{
			name:     "Creation of a new UserStore with a nil gorm.DB instance",
			db:       nil,
			expected: &UserStore{},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			result := NewUserStore(tc.db)

			assert.Equal(t, tc.expected, result)
		})
	}

	t.Run("Multiple invocations of the NewUserStore function", func(t *testing.T) {

		defer func() {
			if r := recover(); r != nil {
				t.Logf("Panic encountered so failing test. %v", r)
				t.Fail()
			}
		}()

		dbMock1, _, _ := sqlmock.New()
		dbMock2, _, _ := sqlmock.New()
		gormDB1, _ := gorm.Open("postgres", dbMock1)
		gormDB2, _ := gorm.Open("postgres", dbMock2)

		result1 := NewUserStore(gormDB1)
		result2 := NewUserStore(gormDB2)

		assert.NotNil(t, result1)
		assert.NotNil(t, result2)

		assert.Equal(t, gormDB1, result1.db)
		assert.Equal(t, gormDB2, result2.db)

		assert.NotEqual(t, result1, result2)
	})
}
