// ********RoostGPT********
/*
Test generated by RoostGPT for test GoReadOnlyTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=Handler_UnfollowUser_6114d3d2b5
ROOST_METHOD_SIG_HASH=Handler_UnfollowUser_44ddaba28f

FUNCTION_DEF=func (h *Handler) UnfollowUser(ctx context.Context, req *pb.UnfollowRequest) (*pb.ProfileResponse, error) // UnfollowUser unfollow a user

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: golang-grpc-realworld-example/handler/profile_test.go
Test Cases:
    [TestUnfollowUser]

Scenario 1: User successfully unfollows another user

Details:
   This test verifies that a user can successfully unfollow another user in the system.

Execution:
    Arrange: We create two users in the system, UserA and UserB, and make UserA follow UserB.
    Act: UserA sends an UnfollowRequest to unfollow UserB.
    Assert: The returned response should be a ProfileResponse containing UserB's profile with the boolean attribute "Following" as false.

Validation:
    The assertion checks that UserA is no longer following UserB. Adds value to confirm the success of the unfollow functionality.

Scenario 2: User tries to unfollow themselves

Details:
   This test should ensure that a user cannot unfollow themselves.

Execution:
    Arrange: We create a user, UserA, in the system.
    Act: UserA sends an UnfollowRequest to unfollow himself.
    Assert: An error with the status code "InvalidArgument" should be returned.

Validation:
    The assertion checks that users cannot unfollow themselves. It's important because it prevents misuse and errant behavior.

Scenario 3: Unauthenticated user tries to unfollow a user

Details:
   This test intends to ensure that unauthenticated users cannot perform any action related to following.

Execution:
    Arrange: We create a user, UserA, in the system. A request is made by an unauthenticated user
    Act: The unauthenticated user sends an UnfollowRequest to unfollow UserA.
    Assert: An error with the status code "Unauthenticated" should be returned.

Validation:
    The assertion checks that unauthenticated users are prohibited from performing unfollow actions. It's important to protect user privacy and unauthorized data access.

Scenario 4: User tries to unfollow a non-existing user

Details:
   This test should confirm that the system disallows attempts to unfollow users who do not exist in the system.

Execution:
    Arrange: We create a user, UserA, in the system. UserA tries to unfollow a non-existing user
    Act: UserA sends an UnfollowRequest to unfollow the non-existing user.
    Assert: An error with the status code "NotFound" should be returned.

Validation:
    The assertion checks that attempts to unfollow non-existent users are blocked. Preventing null-pointer anomalies and errant behavior.

Scenario 5: User tries to unfollow a user they are not following

Details:
   This test is meant to verify that a user can't unfollow another user they are not currently following.

Execution:
    Arrange: We create two users in the system, UserA and UserB. UserA is not following UserB.
    Act: UserA sends an UnfollowRequest to unfollow UserB.
    Assert: An error with the status code "Unauthenticated" should be returned.

Validation:
   The assertion checks that a user cannot unfollow another user if they are not following them initially. This is required to maintain appropriate behavioral constraints.
*/

// ********RoostGPT********

package handler

import (
	"context"
	"testing"

	"github.com/raahii/golang-grpc-realworld-example/auth"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/raahii/golang-grpc-realworld-example/proto"
	"github.com/stretchr/testify/assert"
)

func TestUnfollowScenarios(t *testing.T) {
	h, cleaner := setUp(t)
	defer cleaner(t)

	fooUser := &model.User{Username: "foo", Email: "foo@example.com", Password: "secret"}
	barUser := &model.User{Username: "bar", Email: "bar@example.com", Password: "secret"}
	users := []*model.User{fooUser, barUser}

	for _, user := range users {
		if err := h.us.Create(user); err != nil {
			t.Fatalf("failed to create initial user record: %v", err)
		}
	}

	if err := h.us.Follow(fooUser, barUser); err != nil {
		t.Fatalf("failed to create initial user relationship: %v", err)
	}

	token, err := auth.GenerateToken(fooUser.ID)
	if err != nil {
		t.Error(err)
	}

	scenarios := []struct {
		name    string
		request *proto.UnfollowRequest
		want    *proto.Profile
		wantErr bool
	}{
		{
			name:    "User successfully unfollows another user",
			request: &proto.UnfollowRequest{Username: barUser.Username},
			want:    barUser.ProtoProfile(false),
			wantErr: false,
		},
		{
			name:    "User tries to unfollow themselves",
			request: &proto.UnfollowRequest{Username: fooUser.Username},
			want:    nil,
			wantErr: true,
		},
		{
			name:    "Unauthenticated user tries to unfollow a user",
			request: &proto.UnfollowRequest{Username: barUser.Username},
			want:    nil,
			wantErr: true,
		},
		{
			name:    "User tries to unfollow a non-existing user",
			request: &proto.UnfollowRequest{Username: "non-existing"},
			want:    nil,
			wantErr: true,
		},
		{
			name:    "User tries to unfollow a user they are not following",
			request: &proto.UnfollowRequest{Username: barUser.Username},
			want:    nil,
			wantErr: true,
		},
	}

	for _, s := range scenarios {
		t.Run(s.name, func(t *testing.T) {
			ctx := ctxWithToken(context.Background(), token)
			res, err := h.UnfollowUser(ctx, s.request)

			if (err != nil) != s.wantErr {
				t.Errorf("%q: handler.UnfollowUser() error = %v, wantErr %v", s.name, err, s.wantErr)
			}

			if !s.wantErr {
				assert.Equal(t, res.GetProfile().GetUsername(), s.want.GetUsername())
				assert.Equal(t, res.GetProfile().GetBio(), s.want.GetBio())
				assert.Equal(t, res.GetProfile().GetImage(), s.want.GetImage())
				assert.Equal(t, res.GetProfile().GetFollowing(), s.want.GetFollowing())
			}
		})
	}
}
